name: "Publish documentation"
on:
  push:
    branches:
      - "main"

jobs:
  build:
    permissions:
      id-token: "write"
      pages: "write"

    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: "actions/checkout@v4"

      - id: "setup-node"
        name: "Set up Node.js"
        uses: "actions/setup-node@v6"

      - id: "install-dependencies"
        name: "Install Node.js dependencies"
        run:  npm install
      - id: "build"
        name: "Build documentation"
        run: |
          npm run docs
          cp docs/modules.html docs/index.html # I prefer the modules doc
      - id: deployment
        name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "docs/"
  deploy:
    permissions:
      id-token: "write"
      pages: "write"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v4"